# Banco de Dados (Substitua pelos dados do seu Supabase)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres.tmryemwcydwnpytlszqn
quarkus.datasource.password=${SUPABASE_DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres

# Configurações da Bunny.net
bunny.storage.zone=nome-da-sua-storage-zone
bunny.api.key=sua-chave-api-da-storage-zone
bunny.pull.url=https://b-cdn.net

# Permitir chamadas do Frontend (CORS)
quarkus.http.cors=true
quarkus.http.cors.origins=*