# Banco de Dados - Supabase (Seguro via Variáveis de Ambiente)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres.tmryemwcydwnpytlszqn
quarkus.datasource.password=${SUPABASE_DB_PASSWORD}
quarkus.datasource.jdbc.url=${SUPABASE_DB_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require}
# Força o Quarkus a ignorar a checagem de metadados e usar o dialeto correto direto
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# Reativa a checagem de esquema baseada nas suas entidades Java
quarkus.hibernate-orm.schema-management.strategy=validate



# Configurações da Bunny.net (Seguro via Variáveis de Ambiente)
# Se não for usar localmente agora, coloque valores fictícios para destravar o boot:
bunny.api.key=${BUNNY_API_KEY:mock-key-para-teste-local}
bunny.pull.url=${BUNNY_PULL_URL:http://localhost}
bunny.storage.zone=${BUNNY_STORAGE_ZONE:mock-zone}

# Configuração Nativa de CORS para Quarkus 3.x (Via Vert.x)
quarkus.rest.cors=true
quarkus.rest.cors.origins=*
quarkus.rest.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.rest.cors.headers=accept,authorization,content-type,origin

